version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
  nginx:
    image: nginx:latest
    ports:
      - "8001:8001"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./media:/media
      - ./static:/static
    depends_on:
      - web
  web:
    environment:
    - PRODUCTION=1
    build: .
    command: bash -c "gunicorn project.wsgi -w 4 -b 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./static:/static
      - ./media:/media
    depends_on:
      - db
